# Generated by Django 2.0.1 on 2018-01-31 15:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('header_image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mashcast.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('header_image_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('categories', models.ManyToManyField(to='mashcast.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mashcast.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('header_image_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mashcast.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('url', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mashcast.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('header_image_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('feed_url', models.URLField()),
                ('description', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('schedule_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashcast.Author')),
                ('categories', models.ManyToManyField(to='mashcast.Category')),
                ('channels', models.ManyToManyField(to='mashcast.Channel')),
                ('countries', models.ManyToManyField(to='mashcast.Country')),
                ('languages', models.ManyToManyField(to='mashcast.Language')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mashcast.Podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashcast.Podcast'),
        ),
        migrations.AddField(
            model_name='channel',
            name='countries',
            field=models.ManyToManyField(to='mashcast.Country'),
        ),
        migrations.AddField(
            model_name='channel',
            name='languages',
            field=models.ManyToManyField(to='mashcast.Language'),
        ),
        migrations.AddField(
            model_name='channel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mashcast.Channel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
